spring:
  application:
    name: smartstock-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/smartjava
    username: postgres
    password: 987123
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
server:
  port: 8081
